#The data files needed to run this example code can be downloaded from the following sourceforge project: 

#sourceforge.net/projects/fastqsim/files 


inputfastq=Example.fq #This file can be downloaded from sourceforge.net/projects/fastqsim/files  The file is contained in "example_data.tgz" 
inputref=ref/hs_ref_GRCH38.fa #The human reference file can be generated by running the included script:  LoadHumanRef.sh 


#characterization
#------------------

#using -sam input
sh FASTQcharacterize.sh -input $inputfastq -reference $inputref -sam Example.sam

#using BLAST alignment tool
sh FASTQcharacterize.sh -input $inputfastq -reference $inputref

#Flag -plothistogram added to plot spiking statistics 
sh FASTQcharacterize.sh -input $inputfastq -reference $inputref -plothistogram


#spiking
#-----------

#For spiking an "$inputfastq" background file with a characterization profile described in file "Example5summary.csv" 
sh FASTQspike.sh $inputfastq Examplesummary.csv -source 0.5 ecoli.fasta True -source 1 EU496103_with_xis_AAV.fasta True -o SpikedResultExample -threads 10

#With -plothistogram flag for plotting spike statistics 
sh FASTQspike.sh $inputfastq Examplesummary.csv -source 20 ecoli.fasta True -source 200 EU496103_with_xis_AAV.fasta True -plothistogram -o SpikedResultExample -threads 10

#With the 'nobackground' flag replacing a background input fastq file (can be used for testing coverage) 
sh FASTQspike.sh -nobackground Examplesummary.csv -source 20 ecoli.fasta True -source 200 EU496103_with_xis_AAV.fasta True -plothistogram -o SpikedResultExample_NoBackground -threads 10

#using a built-in error profile. There is no need to run the characterization tool to use a default error profile. 
sh FASTQspike.sh -nobackground -platform ion -source 20 ecoli.fasta True -source 200 EU496103_with_xis_AAV.fasta True -o SpikedResultExample_NoBackground -threads 10 